# Generated by Django 3.2.12 on 2022-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentname',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
